In [2]:
import numpy as np

In [59]:
data = np.loadtxt("D:\JN\Musulmon\K ta yaqin qo'shni usuli\datasets\Housing_processed.csv", 
                  skiprows=1, 
                  delimiter=',')

X = data[:, 1:]
Y = data[:, 0]

<>:1: SyntaxWarning: invalid escape sequence '\J'
<>:1: SyntaxWarning: invalid escape sequence '\J'
C:\Users\muxitdinov_h\AppData\Local\Temp\ipykernel_3092\2438413075.py:1: SyntaxWarning: invalid escape sequence '\J'
  data = np.loadtxt("D:\JN\Musulmon\K ta yaqin qo'shni usuli\datasets\Housing_processed.csv",


In [60]:
X

array([[7.42e+03, 4.00e+00, 2.00e+00, ..., 2.00e+00, 1.00e+00, 2.00e+00],
       [8.96e+03, 4.00e+00, 4.00e+00, ..., 3.00e+00, 0.00e+00, 2.00e+00],
       [9.96e+03, 3.00e+00, 2.00e+00, ..., 2.00e+00, 1.00e+00, 1.00e+00],
       ...,
       [3.62e+03, 2.00e+00, 1.00e+00, ..., 0.00e+00, 0.00e+00, 0.00e+00],
       [2.91e+03, 3.00e+00, 1.00e+00, ..., 0.00e+00, 0.00e+00, 2.00e+00],
       [3.85e+03, 3.00e+00, 1.00e+00, ..., 0.00e+00, 0.00e+00, 0.00e+00]],
      shape=(545, 12))

In [61]:
Y

array([13300000., 12250000., 12250000., 12215000., 11410000., 10850000.,
       10150000., 10150000.,  9870000.,  9800000.,  9800000.,  9681000.,
        9310000.,  9240000.,  9240000.,  9100000.,  9100000.,  8960000.,
        8890000.,  8855000.,  8750000.,  8680000.,  8645000.,  8645000.,
        8575000.,  8540000.,  8463000.,  8400000.,  8400000.,  8400000.,
        8400000.,  8400000.,  8295000.,  8190000.,  8120000.,  8080940.,
        8043000.,  7980000.,  7962500.,  7910000.,  7875000.,  7840000.,
        7700000.,  7700000.,  7560000.,  7560000.,  7525000.,  7490000.,
        7455000.,  7420000.,  7420000.,  7420000.,  7350000.,  7350000.,
        7350000.,  7350000.,  7343000.,  7245000.,  7210000.,  7210000.,
        7140000.,  7070000.,  7070000.,  7035000.,  7000000.,  6930000.,
        6930000.,  6895000.,  6860000.,  6790000.,  6790000.,  6755000.,
        6720000.,  6685000.,  6650000.,  6650000.,  6650000.,  6650000.,
        6650000.,  6650000.,  6629000.,  6615000., 

In [7]:
data.shape

(545, 13)

In [62]:
num_train = 300
num_val = 145
num_test = 100

In [63]:
indices = np.arange(data.shape[0])
indices

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [64]:
indices = np.arange(data.shape[0])
np.random.shuffle(indices)
indices

array([ 26, 215, 339,  88, 379, 139,  86, 485,  15, 188, 141, 279, 103,
       260, 138,  51, 348, 107, 391, 354, 192, 306, 479, 413, 269, 361,
       417, 298, 170, 351, 405, 265, 466, 284, 440, 353,  31, 484, 442,
        70, 268, 187, 231, 160, 415, 471, 297, 199, 293, 455, 242, 123,
       420, 122, 336, 343,  99, 365, 207, 127, 461, 113, 515, 292, 513,
       477, 332, 262, 128,  59, 124, 273,  48, 511, 286,  23, 184, 197,
       478, 494, 224, 334, 342, 109,  87, 171, 174,   1, 115, 355, 322,
       371, 350,  49, 503, 152, 309,  76,  10, 530, 544, 156, 325, 337,
       210, 205, 233, 522,  96,  83, 437, 312, 257, 151, 244, 295, 398,
       178, 157, 374, 445, 449, 134, 497, 175, 247, 101, 119, 385, 486,
       301,  78, 428, 168, 290, 158, 425,  39,  30, 130, 136,  54, 327,
       280, 528, 289, 218,   3, 294, 237, 245, 149,  32, 296, 539,  58,
        63, 403, 452, 100, 493, 318, 208, 243, 476, 230, 469, 538, 514,
       198,  66, 275,  67, 473,  12, 317, 512, 540, 299,  85,  1

In [65]:
indices = np.arange(data.shape[0])
np.random.seed(42) # bu bizga shuffle qilib random qilganimizda HAR DOIM BIR XIL Qiymat chiqishiga yordam beradi
np.random.shuffle(indices)
indices

array([316,  77, 360,  90, 493, 209, 176, 249, 516, 426,   6, 497, 422,
       424, 529, 499, 498,  55, 476, 486,  72, 163, 538, 174, 304,   2,
       463, 184,  10, 512,  70, 398,  79, 483, 429, 296, 210, 431, 394,
       523, 158, 367,  76, 199, 451, 255,  83, 137, 473, 540,  30, 517,
       284, 324, 440, 543,   9, 533, 274, 465, 341, 390, 225, 461, 245,
        84,  73, 185, 247,  78, 377, 148, 354,  82, 442,  75, 228, 218,
        68, 531,  63, 307, 104,  86, 537,  33, 500, 305,   0,  11, 271,
        22, 365, 182,  89, 117, 131, 140, 101, 149, 467,  18, 208, 153,
        15, 357,  39,  54, 155,  46,  93, 335, 412, 471, 237, 544, 470,
       511, 361, 364, 520, 299, 371, 373, 165, 541, 173, 393,  69, 331,
       333, 132, 172, 124, 388, 521, 503, 167, 368, 301, 527, 382, 235,
       302, 460, 439,  19, 376,  56, 229, 277, 375, 265, 280, 480, 220,
        25, 286,  42, 395, 425, 195, 452, 154, 126, 363, 370,  31, 113,
       222, 462, 177,  57, 244,  24,  17, 402,  66, 238, 272, 26

In [71]:
indices = np.arange(data.shape[0])
np.random.seed(42) # bu bizga shuffle qilib random qilganimizda HAR DOIM BIR XIL Qiymat chiqishiga yordam beradi
np.random.shuffle(indices)
print(indices)


X_tr = X[indices[:num_train]]
y_tr = Y[indices[:num_train]]

X_va = X[indices[num_train:num_train+num_val]]
y_va = Y[indices[num_train:num_train+num_val]]

X_te = X[indices[num_train+num_val:]]
y_te = Y[indices[num_train+num_val:]]

[316  77 360  90 493 209 176 249 516 426   6 497 422 424 529 499 498  55
 476 486  72 163 538 174 304   2 463 184  10 512  70 398  79 483 429 296
 210 431 394 523 158 367  76 199 451 255  83 137 473 540  30 517 284 324
 440 543   9 533 274 465 341 390 225 461 245  84  73 185 247  78 377 148
 354  82 442  75 228 218  68 531  63 307 104  86 537  33 500 305   0  11
 271  22 365 182  89 117 131 140 101 149 467  18 208 153  15 357  39  54
 155  46  93 335 412 471 237 544 470 511 361 364 520 299 371 373 165 541
 173 393  69 331 333 132 172 124 388 521 503 167 368 301 527 382 235 302
 460 439  19 376  56 229 277 375 265 280 480 220  25 286  42 395 425 195
 452 154 126 363 370  31 113 222 462 177  57 244  24  17 402  66 238 272
 261 353  94 180 192 250  23 502 456 518   5 116  45 311 312  16  48 204
 414   3 268 340  60 196 524 110 362 297  29 234 211  26   7 181  50 108
  37 157 519 118 407 114 515 203 175 380 231 144 194 420 433 248 289 415
 505 141 416  67 281 227 168 188 329 428 496 193  8

In [72]:
x_tr_max = X_tr.max(axis=0)
print(x_tr_max)


X_tr = X_tr / x_tr_max
X_va = X_va / x_tr_max
X_te = X_te / x_tr_max

[1.62e+04 6.00e+00 3.00e+00 4.00e+00 1.00e+00 1.00e+00 1.00e+00 1.00e+00
 1.00e+00 3.00e+00 1.00e+00 2.00e+00]


In [82]:
D = np.zeros((num_val, num_train))
# val to'plam bo'yicha loop
i = 0
while i < num_val:
    # train to'plam bo'yicha loop
    j = 0
    while j < num_train:
        # Manhattan
        # D[i, j] = np.sum(np.abs(X_va[i] - X_tr[j]))
        # Euclidean
        D[i, j] = np.sqrt(np.sum((X_va[i] - X_tr[j])**2))
        j += 1 # j = j + 1
    i += 1 # i = i + 1
D_argsort = np.argsort(D, axis=1)

In [83]:
k = 1
k_best = 2
E_best = 1e10
while k <= 50:
    y_pred = y_tr[D_argsort[:, :k]]
    y_pred = np.mean(y_pred, axis=1)
    print(y_pred)
    E = np.mean(np.abs(y_pred - y_va))

    if E < E_best:
        E_best = E
        k_best = k

    k += 1 # k = k + 1

print(f"k={k_best}, E={E:.4f}")

[4025000. 5425000. 3080000. 2940000. 5600000. 5600000. 4305000. 4123000.
 4690000. 4403000. 3640000. 4403000. 2695000. 3640000. 6790000. 5250000.
 3640000. 4690000. 1767150. 2275000. 4305000. 3500000. 4382000. 2408000.
 1890000. 3325000. 3010000. 4900000. 4200000. 3710000. 2940000. 3675000.
 2380000. 5530000. 3150000. 4620000. 4130000. 4193000. 8855000. 5495000.
 3080000. 1890000. 3325000. 5215000. 6895000. 6090000. 5215000. 4193000.
 3570000. 5740000. 6195000. 2660000. 5075000. 3500000. 4690000. 3500000.
 5740000. 2450000. 7140000. 2940000. 3710000. 6510000. 3423000. 3710000.
 4200000. 2380000. 7525000. 5145000. 4025000. 3990000. 7525000. 3640000.
 4515000. 3325000. 8645000. 8855000. 8960000. 7455000. 4613000. 5600000.
 2450000. 3325000. 3850000. 4200000. 6090000. 4200000. 3430000. 3710000.
 5110000. 6090000. 1750000. 6650000. 3500000. 1750000. 8645000. 4473000.
 4007500. 4690000. 4270000. 3640000. 3710000. 5600000. 4585000. 3570000.
 6790000. 5810000. 3423000. 4613000. 2520000. 43050

In [76]:
D = np.zeros((num_test, num_train))
# val to'plam bo'yicha loop
i = 0
while i < num_test:
    # train to'plam bo'yicha loop
    j = 0
    while j < num_train:
        # D[i, j] = np.sum(np.abs(X_te[i] - X_tr[j]))
        D[i, j] = np.sqrt(np.sum((X_te[i] - X_tr[j])**2))
        j += 1 # j = j + 1
    i += 1 # i = i + 1
D_argsort = np.argsort(D, axis=1)

In [ ]:
y_pred = y_tr[D_argsort[:, :k_best]]
y_pred = np.mean(y_pred, axis=1)
E = np.mean(np.abs(y_pred - y_te))
print(f"k={k_best}, Test xatoligi: {E:.4f}")

k=9, Test xatoligi: 907311.6111
